config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users do
    # resources :booking, only: %i[create new]
    resources :user_ratings, only: %i[create new show index]
    resources :booking, only: %i[show index]
  end
  resources :bookings, only: %i[destroy update]
  resources :user_ratings, only: %i[destroy]

  resources :user_games, only: [:destroy, :create, :new, :show]
  resources :user_games, only: [:destroy]

  get "/my_games", to: "user_games#mine", as: :mine

  resources :user_games do
    resources :bookings, only: %i[create new]
  end

  resources :game_ratings

  resources :games

  get "/dashboard", to: "pages#dashboard", as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :user_game
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: ["pending", "accepted", "declined"] }
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :year, presence: true
  validates :min_players, presence: true
  validates :max_players, presence: true
  validates :playtime, presence: true
  validates :image_url, presence: true
  validates :average_rating, presence: true
  has_many :user_games, dependent: :destroy
end

app/models/game_rating.rb
class GameRating < ApplicationRecord
  belongs_to :game_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_games, dependent: :destroy
  has_many :bookings

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :address, presence: true
  # validates :phone_number, presence: true
  # validates :plz, presence: true
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  # validates :title, uniqueness: true, presence: true
  # validates :availibility, presence: true
  # validates :renting_deposit, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :renting_price, :renting_deposit ],
    associated_against: {
      game: [ :title, :description ],
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
  belongs_to :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :payment_method, :phone_number, :plz])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @user_game = UserGame.find(params[:user_game_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @user_game = UserGame.find(params[:user_game_id])
    @booking.user = current_user
    @booking.user_game = @user_game
    @booking.status = "pending"

    if @booking.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if params[:status] == "accept"
      @booking.status = "accepted"
    elsif params[:status] == "decline"
      @booking.status = "declined"
    end
    @booking.save
    redirect_to dashboard_path, notice: "Status updated"


  end


  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = booking.destroy
    redirect_to root_path, notice: "Booking request canceled"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/game_ratings_controller.rb
class GameRatingsController < ApplicationController
  def index
    @game_ratings = GameRating.all
  end

  def show
    @game_rating = GameRating.find(game_id.params[@user_id])
  end

  private

  def set_game_rating
    @game_rating = GameRating.find(params[@user_id])
  end

  def game_rating_params
    params.require(:game_rating).permit(:coment, :rating, :game_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.destroy
    redirect_to games_path, notice: "Game succesfully deleted"
  end

    private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :editor, :category, :year, :min_players, :max_players, :playtime, :image_url, :average_rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  # def library
  #   @user_game = UserGame.find(current_user.id)
  # end

  def dashboard
    @bookings = Booking.where(user_id: current_user)
    # @user_game = UserGame.find(current_user.id)
  end

  # def dashboard
  #   @bookings = current_user.bookings
  # end
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
  before_action :set_user_game, only: [:show, :destroy]

  def index
    if params[:query].present?
      @user_games = UserGame.global_search(params[:query]).where.not(user_id: current_user)

    else
      @user_games = UserGame.where.not(user_id: current_user)
    end
  end

  def mine
    @user_games = UserGame.where(user_id: current_user)
  end

  def new
    @user_game = UserGame.new
  end

  def create
    @user_game = UserGame.new(user_games_params)
    @user_game.user = current_user
    @user_game.availibility = true

    if @user_game.save
      redirect_to mine_path(@user_game)
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @user_game = UserGame.find(params[:id])
    @user_game.destroy
    redirect_to user_games_path
  end

  private

  def set_user_game
    @user_game = UserGame.find(params[:id])
  end

  def user_games_params
    params.require(:user_game).permit(:renting_price, :renting_deposit, :game_id)
  end
end

app/controllers/user_ratings_controller.rb
class UserRatingsController < ApplicationController
  def index
    @user_ratings = UserRating.all
  end

  def show
    @user_rating = UserRating.find(params[:user_id])
  end

  def destroy
    @user_rating = UserRating.destroy
    redirect_to user_path(:user_id)
  end

  def edit
  end

  def new
    @user_rating = UserRating.new
  end

  def create
    @user_rating = UserRating.new
    if @user_rating.save
      redirect_to user_path(:user_id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_user_rating
    @user_rating = UserRating.find(params[:user_id])
  end

  def user_rating_params
    params.require(:user_rating).permit(:comment, :rating, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Status:</strong>
    <%= booking.status %>
  </p>

  <p>
    <strong>Start Date:</strong>
    <%= bookmark.start_date %>
  </p>

  <p>
    <strong>End Date</strong>
    <%= bookmark.end_date %>
  </p>


</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [user_game, booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit :submit %>
<% end %>

app/views/bookings/index.html.erb
<h1>Booking Plataform</h1>

<p><% @bookings.each do |l| %>
<%= l.user_game_id %>
<%= l.status %>
<%= l.start_date %>
<%= l.end_date %>
<%= l.user_id %>
<% end %>

<button class="btn btn-primary">  <%= link_to "New booking", new_game_booking_path(:game_id) %>
<button class="btn btn-primary">  <%= link_to "Delete booking", booking_path(:id) %>
<button class="btn btn-primary">  <%= link_to "All bookings", user_booking_index_path(:id) %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render "form", booking: @booking, user_game: @user_game %>

<% # link_to "Back bookings", user_booking_index_path %>

app/views/bookings/show.html.erb
<h1>Booking</h1>

<p><% @booking.each do |l| %>
<%= l.user_game_id %>
<%= l.user_id %>
<%= l.status %>
<%= l.start_date %>
<%= l.end_date %>
<%= l.user_id %>
<button class="btn btn-primary"> <%= link_to "delete booking", booking_path(@booking),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
<% end %>

<button class="btn btn-primary">  <%= link_to "All bookings", user_booking_index_path(:id) %>

app/views/game_ratings/index.html.erb
<h1>Games ratings</h1>

<p><% @games_ratings.each do |l| %>
<%= l.game_id %>
<%= l.comment %>
<%= l.rating %>
<%= l.description %>
<button class="btn btn-primary"> <%= link_to "delete Rating", game_ratings_path(:id),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
<% end %>
<% end %>

app/views/game_ratings/new.html.erb
<%= simple_form_for @games_ratings do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/game_ratings/show.html.erb
<h1>Game Ratings</h1>

<p><% @game_ratings.each do |l| %>
<%= l.comment %>
<%= l.rating %>
<button class="btn btn-primary"> <%= link_to "delete rating", game_rating_path(:id),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
<% end %>

<button class="btn btn-primary">  <%= link_to "All game ratings", game_ratings_index_path(:id) %>

app/views/games/index.html.erb
<h1>Games</h1>

<p><% @games.each do |l| %>
<div class="card row justify-content-center" style="">
  <ul>
    <div class="card" style="justify-content-center width: 450px; height: 350px;"><%= image_tag "#{l.image_url}" %></div>
    <li><%= l.title %></li>
    <li><%= l.year %></li>
    <li><%= l.min_players %></li>
    <li><%= l.max_players %></li>
    <li><%= l.playtime %></li>
    <li><%= l.description %></li>
  </ul>
</div>
<% end %>
<%# <%= button_to "Add game to My List", new_user_game_path(@user_game[:id]) %> %>

app/views/games/show.html.erb
<h1>Game</h1>
  <p>
    <strong>Name:</strong>
    <%= @game.title %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= @game.year %>
  </p>

  <p>
    <strong>Max Players</strong>
    <%= @game.max_players %>
  </p>
  <p>
    <strong>Min Players</strong>
    <%= @game.min_players %>
  </p>

  <p>
    <strong>playtime</strong>
    <%= @game.playtime %>
  </p>

  <p>
    <strong>Average Rating</strong>
    <%= @game.average_rating %>
  </p>

  <p>
    <strong>description</strong>
    <%= @game.description %>
  </p>





</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ludo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1 style="text-align: center; margin: 30px; text-shadow: 1px 1px 1px #bbb, 2px 2px 1px #220c0c;"> Bookings </h1>
<div class="container" style="">
  <div class="row d flex justify-content-between", style="">
    <% @bookings.each do |booking|  %>
    <div class="card-trip" style="width: 350px; margin: 30px;
margin-top: 30px;">
      <img src="<%= "#{booking.user_game.game.image_url}" %>" />
      <div class="card-trip-infos">
        <div>
          <h5 style="text-align: center;"><%= Game.find(booking.user_game.id).title %></h5>

          <p><strong>Starting Date</strong></p>
          <p><%= booking.start_date %></p>
          <p><strong>Ending Date</strong></p>
          <p><%= booking.end_date %></p>
          <p><strong><%= booking.status %></strong></p>
        </div>
        <h2 class="card-trip-pricing"><p> </p></h2>
        <%= button_to "Accept", booking_path(booking, status: "accept"), method: :patch %>
        <%= button_to "Decline", booking_path(booking, status: "decline"), method: :patch %>
        <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
      </div>
    </div>
    <% end %>
  </div>
</div>


<%# <img src="<%= "#{@booking.user_game.image_url}" %>

app/views/pages/home.html.erb
<div class="d-flex justify-content-center align-items-center" style="background-image: url(<%= image_url "https://res.cloudinary.com/dicpef1tv/image/upload/v1669285679/1_nRd0-ZVoNwhjxiwFMrtBCQ_wsye53.jpg" %>); height: 90vh; background-size: cover;background-position: center;opacity-50">
  <div class="lend-info rounded">
    <h1 class="lend-main-heading"> Rent or Lend boardgames easily around your area! </h1>
      <%= link_to '/users/sign_up', remote: true do %>
  <button class="btn btn-primary border-light" style="background-color: #F27B21">Register Here</button>
<% end %>
    <%# <label for="plz">Area code:
    <input type="plz" name="plz" id="plz"> %>
<%#
    <input type="submit" name="Sign up"> %>
  </div>
</div>

<div class="d-flex flex-column justify-content-evenly" style="height: 40vh; background-color: #222222"> </div>

      <%# MAP HEREEEEE %>

<div class="footer d-flex justify-content-center align-items-center flex-row">
  <a href="..." class="About mx-2">About</a>
  <a href="..." class="Pricing mx-2">Pricing</a>
  <a href="..." class="Team mx-2">Team</a>
  <a href="..." class="btn btn-primary mx-2" style="background-color: #08A355">Contact us</a>
</div>

app/views/pages/library.html.erb
<H1> Test</H1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
  <div class="d-flex align-items-center">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://pngimg.com/uploads/dice/dice_PNG54.png" %>
      <% end %>
      <h1><%= link_to "Ludo", "/", class: "nav-link" %></h1>
      <p class="m-0 ms-3">Rent games fast and easy in your area!</p>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item">  <strong>
            <%= link_to "My Bookings", "/dashboard", class: "nav-link border-dark" %>
          </li>
        <li class="nav-item">
            <%= link_to "All Games", user_games_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
            <%= link_to "My Games", mine_path, class: "nav-link" %>
          </strong> </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dicpef1tv/image/upload/v1669285608/images_wpffau.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", "/users/edit" , class: "dropdown-item" %>
<%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/user_games/create.html.erb
<h1>Create a users game</h1>
<%= simple_form_for @user_games do |f| %>
  <%= f.input :availibility %>
  <%= f.input :renting_price %>
  <%= f.input :renting_deposit %>
  <%= f.button :submit %>
<% end %>

app/views/user_games/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <div id="user_games">
        <%= form_with url: user_games_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a game"
          %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h3 class="d-flex justify-content-around" >My Lists</h3>

<div class="container">
  <div class="row">

    <% @user_games.each do |l| %>
      <div class="col-6">
        <div class="card-product" style="width: 60vh; margin: 30px">
          <%= link_to user_game_path(l) do  %>
            <img src="<%= "#{l.game.image_url}" %>" />
          <% end %>
          <div class="card-product-infos d-flex justify-content-between" style="margin: 5px">
            <div>
              <%= l.game.title %>
              <p>Min Players</p>
              <%= l.game.min_players %>
              <p>Max Players</p>
              <%= l.game.max_players %>
            </div>
            <div style="margin-left: 8px">
              <p>Playtime</p>
              <%= l.game.playtime %>
              <%# <li><%= l.game.description %>
              <% if l.user == current_user %>
                <%= link_to "Delete Game", user_game_path(l), method: :delete, class: "btn btn-danger"  %>
                <% else %>
              <%= link_to "Rent Game", new_user_game_booking_path(l.id), class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/user_games/mine.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <div id="user_games">
        <%= form_with url: user_games_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a game"
          %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to '/user_games/new', remote: true do %>
  <button class="btn btn-primary" style="float: right; background-color: #F27B21; margin-right: 10px; margin-top: 10px;">Add a game to your List</button>
<% end %>

<h3 class="d-flex justify-content-around" style="margin-top: 10px;" >My Lists</h3>

<div class="container">
  <div class="row">

    <% @user_games.each do |l| %>
      <div class="col-6">
        <div class="card-product" style="margin: 15px; border-radius: 8px">
          <%= link_to user_game_path(l) do  %>
            <img src="<%= "#{l.game.image_url}" %>" />
          <% end %>
          <div class="card-product-infos d-flex justify-content-between" style="margin: 5px">
            <div>
            </div>
            <div style="margin-left: 8px">
              <h3><%= l.game.title %></h3>


                <h6>Renting price: $<%= l.renting_price %></h6>
              <%= "#{l.game.description.first(150)} (...)" %>
              <% if l.user == current_user %>
                <%= button_to "Delete", user_game_path(l), method: :delete, class: "btn btn-danger", style: "border-radius: 8px; margin-top: 8px; margin-left: 235px;" %>
                <% else %>
              <%= button_to "Rent", new_user_game_booking_path(l.id), class: "btn btn-primary", style: "border-radius: 8px; margin-top: 8px; margin-left: 235px;" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/user_games/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Pick Up a game</h3>
        <p>that you would like to lend</p>
        <%= simple_form_for @user_game do |f| %>
          <%= f.association :game, placeholder: 'Your game list title' %>
          <%= f.input :renting_price %>
          <%= f.input :renting_deposit %>
          <%= f.submit class: 'btn btn-primary' %>
          <%  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_games/show.html.erb
<div class="container">
  <div class="container row flex-row">
    <div class="card-category col-10 p-2 border-bottom sh bg-body rounded ">
      <ul class="game_card justify-content-center align-items-center flex-row">
        <img src="<%= "#{@user_game.game.image_url}" %>" />
          <p class= "title"><strong><%= @user_game.game.title %></p></strong></li>
          <li><strong>Year</strong>
          <p><%= @user_game.game.year %></p></li>
          <li><strong>Minimum Players</strong>
          <p><%= @user_game.game.year %></p></li>
          <li><strong>Maximum Players</strong>
          <p><%= @user_game.game.max_players %></p></li>
          <li><strong>Playtime</strong>
          <p><%= @user_game.game.playtime %> mins</p></li>
            <li><strong>description</strong>
          <p><%= @user_game.game.description %></p></li>
        </ul>
      <div class ="">
        <div class="d-flex justify-content-between" style="margin-right:-491px;">
          <p> <%= @user_game.user.address %> </strong> <i class="fa-solid fa-location-dot"> </i><strong></p>
          <strong> Renting price: <%= @user_game.renting_price %> €</strong></p>
        </div>
        <%= button_to "Rent Game", new_user_game_booking_path(@user_game.id) %>
      </div>
    </div>
  </div>
</div>

app/views/user_ratings/create.html.erb
<h1>Create a rating</h1>
<%= simple_form_for @user_ratings do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/user_ratings/index.html.erb
<h1>User Ratings</h1>

<p><% @user_ratings.each do |l| %>
<%= l.user_id %>
<%= l.comment %>
<%= l.rating %>

<% end %>

app/views/user_ratings/show.html.erb
<h1>User Ratings</h1>

<p><% @user_rating.each do |l| %>
<%= l.user_id %>
<%= l.comment %>
<%= l.rating %>

<% end %>

<button class="btn btn-primary">  <%= link_to "New booking", new_game_booking_path(:game_id) %>
<button class="btn btn-primary">  <%= link_to "Delete booking", booking_path(:id) %>
<button class="btn btn-primary">  <%= link_to "All bookings", user_booking_index_path(:id) %>

app/views/users/index.html.erb
<%# <h1>Users </h1>

<p><% @user.each do |l| %>
<%# <%= l.user_id %> %>
<%# <%= l.first_name %> %>
<%# <%= l.last_name %> %>
<%# <%= l.address %> %>
<%# <%= l.phone_number %> %>
<%# <%= l.rating %> %>
<%# <%= l.plz %> %>
<%# <% end %> %>

<%# <button class="btn btn-primary">  <%= link_to "New booking", new_game_booking_path(:game_id) %> %>
<%# <button class="btn btn-primary">  <%= link_to "All bookings", user_booking_index_path(:id) %> %> %>